api/urls.py
from django.urls import include, path

from api.spectacular.urls import urlpatterns as doc_urls
from users.urls import drf_urlpatterns as user_urls
from blog.urls import drf_urlpatterns as blog_urls
from rating.urls import drf_urlpatterns as rating_urls
from subscription.urls import drf_urlpatterns as subscriptions_urls

app_name = 'api'
urlpatterns = [path(r'auth/', include('djoser.urls.jwt')),]

urlpatterns += doc_urls
urlpatterns += user_urls
urlpatterns += blog_urls
urlpatterns += rating_urls
urlpatterns += subscriptions_urls

blog/urls.py
from django.urls import path, include
from rest_framework import routers

from blog.api.views import comments as api_comms
from blog.api.views import posts as api_posts
from blog.api.views.categories import CategoryViewSet
from blog.views import posts, comments, common

app_name = 'blog'

urlpatterns = [
    path('index/', common.HomeView.as_view(), name='index'),
    path('all/', posts.PostListView.as_view(), name='posts'),
    path('<int:pk>/', posts.PostDetailView.as_view(), name='post-detail'),
    path('create/', posts.CreatePost.as_view(), name='create-post'),
    path('<int:pk>/edit/', posts.EditPost.as_view(), name='edit-post'),
    path('<int:pk>/delete/', posts.DeletePost.as_view(), name='delete-post'),

    path('<int:post_pk>/post-comment/', comments.CommentCreate.as_view(), name='create-comment'),
    path('<int:post_pk>/reply/<int:comment_pk>', comments.CommentCreate.as_view(), name='reply-comment'),
    path('<int:post_pk>/edit-comment/<int:comment_pk>/', comments.CommentEdit.as_view(), name='edit-comment'),
    path('<int:post_pk>/delete-comment/<int:comment_pk>/', comments.CommentDelete.as_view(), name='delete-comment'),
]

router = routers.DefaultRouter()
router.register(r'category', CategoryViewSet, 'categories')
router.register(r'post', api_posts.PostViewSet)
router.register(r'post/(?P<post_id>\d+)/comment', api_comms.CommentViewSet, 'comment')

drf_urlpatterns = [
    path('', include(router.urls)),
    path('post-with-comments/<int:pk>/', api_posts.PostWCommentsRetrieveAPIView.as_view(), name='post-with-comments'),
    path('comment/user/<int:user_id>/', api_comms.CommentListByUserAPIView.as_view(), name='comments-by-user'),
]

config/urls.py
from ckeditor_uploader.views import upload, browse
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import permission_required
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.generic import RedirectView
from drf_spectacular.views import SpectacularAPIView

from . import settings

admin.site.site_header = 'Blog project'
admin.site.site_title = 'Blog'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('blog/', include('blog.urls')),
    path('blog/', include('rating.urls')),
    path('blog/', include('subscription.urls')),
    path('', RedirectView.as_view(url='blog/index/')),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
]

#CKEditor
upload_view = permission_required('blog.add_post')(upload)
browse_view = never_cache(permission_required('blog.add_post')(browse))
urlpatterns += [
    path('ckeditor/upload/', upload_view, name='ckeditor_upload'),
    path('ckeditor/browse/', browse_view, name='ckeditor_browse'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')), ]

rating/urls.py
from django.urls import path

from . import views
from rating.api.views import votes as api_vote

app_name = 'rating'

urlpatterns = [
    path('<int:post_pk>/vote/<str:vote_type>', views.change_rating, name='post-rating'),
    path('<int:post_pk>/vote/<int:comm_pk>/<str:vote_type>', views.change_rating, name='comment-rating'),
]

drf_urlpatterns = [
    path('post/<int:pk>/like', api_vote.PostLikeAPIView.as_view(), name='post-like'),
    path('post/<int:pk>/dislike', api_vote.PostDislikeAPIView.as_view(), name='post-dislike'),
    path('comment/<int:pk>/like', api_vote.CommentLikeAPIView.as_view(), name='comment-like'),
    path('comment/<int:pk>/dislike', api_vote.CommentDislikeAPIView.as_view(), name='comment-dislike'),
]

subscription/urls.py
from django.urls import path

from subscription.views import subscriptions, favorites, feed
from subscription.api.views import favorites as api_favorites
from subscription.api.views import feed as api_feed
from subscription.api.views import subscriptions as api_subs

app_name = 'subscription'

urlpatterns = [
    path('my/', feed.FeedListView.as_view(), name='my-feed'),
    path('my-subscription/', subscriptions.MySubscriptionsListView.as_view(), name='my-subscriptions'),
    path('change-subscription/<str:object_type>/<int:object_id>/<str:action>/',
         subscriptions.ChangeSubscriptionView.as_view(),
         name='change-subscription'),

    path('my-favorites/', favorites.FavoritesView.as_view(), name='my-favorites'),
    path('change-favorite/<int:post_id>/<str:action>/',
         favorites.ChangeFavoriteView.as_view(),
         name='change-favorite'),
]

drf_urlpatterns = [
    path('my_favorites/', api_favorites.MyFavoritesAPIView.as_view(), name='my-favorites'),
    path('post/<int:pk>/add-favorite/', api_favorites.AddFavoriteAPIView.as_view(), name='add-favorite'),
    path('post/<int:pk>/remove-favorite/', api_favorites.RemoveFavoriteAPIView.as_view(), name='remove-favorite'),
    path('my-feed/', api_feed.MyFeedAPIView.as_view(), name='my-feed'),
    path('my-subscriptions/users/', api_subs.MyUserSubscriptionsAPIView.as_view(), name='my-user-subscriptions'),
    path('my-subscriptions/categories/', api_subs.MyCategoriesSubscriptionsAPIView.as_view(), name='my-categories-subscriptions'),
    path('user/<int:pk>/subscribe/', api_subs.UserSubscribeAPIView.as_view(), name='user-subscribe'),
    path('user/<int:pk>/unsubscribe/', api_subs.UserUnsubscribeAPIView.as_view(), name='user-unsubscribe'),
    path('category/<int:pk>/subscribe/', api_subs.CategorySubscribeAPIView.as_view(), name='category-subscribe'),
    path('category/<int:pk>/unsubscribe/', api_subs.CategoryUnsubscribeAPIView.as_view(), name='category-unsubscribe'),
]

users/urls.py
from django.urls import path
from users.views import users
from users.api.views import users as users_api


app_name = 'users'
urlpatterns = [
    path('signup/', users.SignUpView.as_view(), name='signup'),
    path('profile/<int:pk>/', users.UserProfileView.as_view(), name='profile'),
    path('<int:pk>/edit/', users.UserProfileEditView.as_view(), name='profile-edit'),
]

drf_urlpatterns = [
    path('signup/', users_api.SignUpAPIView.as_view(), name='signup'),
    path('change-password/', users_api.ChangePasswordAPIView.as_view(), name='change-password'),
    path('me/', users_api.MeAPIView.as_view(), name='me'),
    path('me/full/', users_api.FullMeAPIView.as_view(), name='me-full'),
    path('users/<int:pk>/', users_api.UserProfileAPIView.as_view(), name='user-profile'),
    path('users/<int:pk>/full/', users_api.FullUserProfileAPIView.as_view(), name='user-profile-full'),
]

blog/api/views/categories.py
from drf_spectacular.utils import extend_schema, extend_schema_view
from rest_framework import filters, viewsets

from blog.api.serializers.endpoints import categories as categories_s
from blog.models import Category
from blog.permissions import IsAdminOrReadOnly
from common.mixins.views import ExtendedView


@extend_schema_view(
    list=extend_schema(
        description='Returns a list of categories.',
        summary='Get a list of categories',
        tags=['Category'],
    ),
    retrieve=extend_schema(
        description='Returns a detailed information about a category.',
        summary='Retrieve information about a category.',
        tags=['Category'],
    ),
    create=extend_schema(
        description="The create action expects the `name` field, creates a new category, and returns it.",
        summary='Create a new category',
        tags=['Category']
    ),
    partial_update=extend_schema(
        description="The partial update action modifies specific fields of a category identified by `id`.",
        summary='Update category name (partial)',
        tags=['Category']
    ),
    update=extend_schema(
        description="The full update action replaces the entire category identified by `id`.",
        summary='Update category name (full)',
        tags=['Category']
    ),
    destroy=extend_schema(
        description="The destroy action deletes a single category identified by `id`.",
        summary='Delete a category',
        tags=['Category']
    )
)
class CategoryViewSet(ExtendedView, viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = categories_s.CategorySerializer
    permission_classes = [IsAdminOrReadOnly]
    filter_backends = [filters.OrderingFilter]
    ordering_fields = ('id', 'title',)
    ordering = ('id',)

    multi_serializer_class = {
        'retrieve': categories_s.CategoryRetrieveSerializer,
    }

    def get_object(self):
        if self.action == 'retrieve':
            return self.queryset.prefetch_related('posts', 'subscribers').get(id=self.kwargs['pk'])
        return super().get_object()

blog/api/views/comments.py
from django.db.models import Q
from django_filters.rest_framework.backends import DjangoFilterBackend
from drf_spectacular.utils import extend_schema, extend_schema_view
from rest_framework import viewsets, generics
from rest_framework.filters import OrderingFilter
from rest_framework.permissions import SAFE_METHODS, AllowAny

from blog.api.serializers.endpoints import comments as comment_s
from blog.filters import IsCommentsExist, CommentFilterSet
from blog.models import Comment
from blog.pagination import CursorCreatedAtPagination
from blog.permissions import IsCommentAuthorPermission
from common.mixins.views import ExtendedView


@extend_schema_view(
    list=extend_schema(
        description="The list action returns all comments of a specific post.",
        summary='List of all comments for a specific post',
        tags=['Comment']
    ),
    retrieve=extend_schema(
        description="The retrieve action returns a single comment identified by `comment_id`.",
        summary='Retrieve a comment from a post',
        tags=['Comment']
    ),
    create=extend_schema(
        description="The create action expects the `name` field, creates a new comment in the post, and returns it.",
        summary='Leave a comment in the post',
        tags=['Comment']
    ),
    partial_update=extend_schema(
        description="The partial update action modifies specific fields of a comment identified by `comment_id`.",
        summary='Partially update a comment',
        tags=['Comment']
    ),
    update=extend_schema(
        description="The update action replaces the entire comment identified by `comment_id`.",
        summary='Fully update a comment',
        tags=['Comment']
    ),
    destroy=extend_schema(
        description="The destroy action deletes a single comment identified by `comment_id`.",
        summary='Delete a comment',
        tags=['Comment']
    ),
)
class CommentViewSet(ExtendedView, viewsets.ModelViewSet):
    # CursorPagination works well in combination with OrderingFilter
    # When trying to do sorting in CommentFilterSet (as it's done in PostFilterSet for PostViewSet) - it breaks

    queryset = Comment.objects.all()
    serializer_class = comment_s.CommentListSerializer

    permission_classes = (
        IsCommentAuthorPermission,
    )
    filter_backends = (
        IsCommentsExist,
        OrderingFilter,
        DjangoFilterBackend,
    )
    ordering = ('-created_at',)
    ordering_fields = ('id', 'rating', 'my_vote', 'created_at')
    filterset_class = CommentFilterSet

    pagination_class = CursorCreatedAtPagination
    lookup_url_kwarg = 'comment_id'

    multi_serializer_class = {
        'list': comment_s.CommentListSerializer,
        'retrieve': comment_s.CommentRetrieveSerializer,
        'create': comment_s.CommentCreateSerializer,
        'partial_update': comment_s.CommentUpdateSerializer,
        'update': comment_s.CommentUpdateSerializer,
    }

    def get_permissions(self):
        if self.request.method in SAFE_METHODS:
            return (AllowAny(),)
        return super().get_permissions()

    def get_queryset(self):
        queryset = Comment.objects.get_comments(
            related_args=('post', 'author',),
            request_user=self.request.user
        ).annotate(
            is_my_comment=Q(author=self.request.user)
        ).filter(
            post_id=self.kwargs.get('post_id')
        )

        return queryset


@extend_schema_view(
    get=extend_schema(
        description="Returns all comments made by a specific user, identified by their `user_id`.",
        summary='All comments by a user',
        tags=['Comment']
    ),
)
class CommentListByUserAPIView(generics.ListAPIView):
    serializer_class = comment_s.CommentListSerializer
    queryset = Comment.objects.all()
    filter_backends = (
        IsCommentsExist,
        OrderingFilter,
        DjangoFilterBackend,
    )
    ordering = ('-created_at',)
    ordering_fields = ('id', 'rating', 'my_vote', 'created_at')
    pagination_class = CursorCreatedAtPagination

    def get_queryset(self):
        user_id = self.kwargs.get('user_id')
        queryset = Comment.objects.get_comments(
            related_args=('post', 'author',),
            request_user=self.request.user
        ).filter(
            author_id=user_id
        )
        return queryset

blog/mixins/views.py
from django.contrib.auth.mixins import AccessMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Prefetch

from blog.models import Post, Comment, Author


class PostDetailQuerySetMixin:
    def get_queryset(self):
        comments_prefetch = Prefetch('comments', Comment.objects.get_comments(
            related_args=['author__profile'],
            request_user=self.request.user
        ))

        qs = Post.objects.select_related(
            'author__user__profile',
            'category',
        ).prefetch_related(
            'favorites',
            comments_prefetch
        ).annotate(
            rating=Post.objects.get_rating_subquery(),
        )

        if self.request.user.is_authenticated:
            qs = Post.objects.get_user_annotate(self.request.user, qs)

        return qs


class PostLoginRequiredAndGetAuthorMixin(AccessMixin):

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        try:
            self.author = Author.objects.get(user=self.request.user)
        except Author.DoesNotExist:
            raise PermissionDenied()
        return super().dispatch(request, *args, **kwargs)


class PostLoginRequiredAndCheckAuthorMixin(AccessMixin):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        # check if the user is the author of the post or is staff
        self.object = self.get_object()
        if self.object.author.user != request.user and not request.user.is_staff:
            raise PermissionDenied()
        return super().dispatch(request, *args, **kwargs)


class CommentLoginRequiredAndCheckAuthorMixin(AccessMixin):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        # check if the user is the author of the post or is staff
        self.object = self.get_object()
        if self.object.author != request.user and not request.user.is_staff:
            raise PermissionDenied()
        return super().dispatch(request, *args, **kwargs)

blog/views/common.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'blog/index.html'

blog/templates/blog/comment_confirm_delete.html
{% extends "base.html" %}

{% block title %}
  <title>Delete comment</title>
{% endblock title %}

{% block content %}
  <h1>Delete comment</h1>
  <p>Are you sure you want to delete this comment?</p>
  <form method="post">
    {% csrf_token %}
      {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Delete</button>
  </form>
{% endblock content %}

blog/templates/blog/comment_form.html
{% extends "base.html" %}

{% block title %}
  <title>Create a comment</title>
{% endblock title %}

{% block content %}
    {% if is_reply %}
        <h1>Reply to {{ comment.author.username }}'s comment</h1>
    {% else %}
        <h1>Comment on {{ blog.title }}</h1>
    {% endif %}
  <form method="post">
    {% csrf_token %}
      {{ form.media }}
      {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Post!</button>
  </form>
{% endblock content %}

blog/templates/blog/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  <title>Main page</title>
{% endblock title %}

{% block content %}
  <h1>Blog</h1>

  <p>Welcome to blog app, a web project built on the Django and Django REST Framework stack, designed for creating,
    managing, and interacting with blog content.</p>
  <p>More information about the project can be found in the project repository's Readme on <a href="YOUR_GITHUB_LINK" target="_blank" class="text-primary">Github</a></p>

  <h2>UML Models</h2>
  <p>A UML diagram of the site's Django model structure is shown below. </p>

  <div>
    {% load static %}
    <img src="{% static "blog/images/db_schema.png" %}" alt="Database Scheme"/>
  </div>
  
  
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block title %}
  <title>Delete blog</title>
{% endblock title %}

{% block content %}
  <h1>Delete blog {{ blog.title }}</h1>
  <p>Are you sure you want to delete this blog?</p>
  <form method="post">
    {% csrf_token %}
      {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Delete</button>
  </form>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load blog_extras %}
{% load bleach_tags %}

{% block title %}
  <title>{% if post.title|length > 20 %}{{ post.title|slice:"20" }}...{% else %}
    {{ post.title }}{% endif %}</title>
{% endblock title %}

{% block content %}
  <div class="container-center">
    <a class="not-styled-link" href="{% url 'users:profile' post.author.user.pk %}">
      <img
          class="img-thumbnail rounded-circle author-photo" src="{{ post.author.user.profile.photo.url }}" width="40"
          height="40" alt="user photo">
    </a>

    <div class="author-name-info">
      <a class="not-styled-link" href="{% url 'users:profile' post.author.user.pk %}">
        <strong>{{ post.author }}</strong>
      </a>
      ,
      <span class="author-object-info">
      {{ post.created_at.date }}
        {% if post.created_at != post.updated_at %}
          (<em>updated_at: {{ post.updated_at }}</em>)
        {% endif %}
    </span>
      <br>
    Category: <a href="{% url 'blog:posts' %}?category={{ post.category }}">{{ post.category }}</a>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="header-container">
        <h1>{{ post.title }}</h1>

      <div class="btn-group-right">
        {% if user.is_staff or request.user == post.author.user %}
            <a class="btn btn-sm btn-warning text-white" href="{% url 'blog:edit-post' post.pk %}">Edit</a>
            <a class="btn btn-sm btn-danger text-white" href="{% url 'blog:delete-post' post.pk %}">Delete</a>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="blog-content image-content">
    {{ post.text|remove_empty_paragraphs|safe|bleach }}
  </div>

  <div class="container-center votes favorites">
    <a href="{% url 'rating:post-rating' post.pk 'LIKE' %}?next={{ request.path }}">
      <svg class="bi pe-none"
           style="margin-right: 3px; color:{% if post.user_vote == 1 %}lightgreen{% else %}gray{% endif %}" width="18"
           height="18">
        <use href="#upvote"></use>
      </svg>
    </a>
    {% include 'includes/rating_color.html' with rating=post.rating %}
    <a href="{% url 'rating:post-rating' post.pk 'DISLIKE' %}?next={{ request.path }}">
      <svg class="bi pe-none me-2"
           style="margin-left: 3px; color:{% if post.user_vote == -1 %}lightcoral{% else %}gray{% endif %}" width="18"
           height="18">
        <use href="#downvote"></use>
      </svg>
    </a>
    {% include 'blog/includes/post_favorites.html' %}
  </div>

  <br>

  <h4><strong>Comments: </strong>{{ post.comments_count }}</h4>
  {% if user.is_authenticated %}
      <a class="btn btn-sm btn-success mb-2 text-white" href="{% url 'blog:create-comment' post.pk %}">Add new comment</a>
  {% else %}
      <a class="btn btn-sm btn-secondary mb-2 text-white" href="{% url 'login' %}?next={% url 'blog:create-comment' post.pk %}">Login</a> to add a new comment.
  {% endif %}

  {% for comment in page_obj %}
    <ul>
      {% include 'blog/includes/blog_comments_recursive.html' %}
    </ul>

  {% endfor %}
  {% include 'includes/base_pagination.html' %}
  <br>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "base.html" %}

{% block title %}
  <title>Create a post</title>
{% endblock title %}

{% block content %}
  <form method="post">
    {% csrf_token %}
      {{ form.media }}
      {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Post!</button>
  </form>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends "base.html" %}

{% block title %}
  <title>All blogs</title>
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-10">
        <h1 class="float-start">
          {{ header }}
        </h1>

        {% if header != 'All posts' %}
          <div class="d-inline-block" style="margin-left: 5%">
            {% if not subscribed %}
              <form method="post" action="{% url 'subscription:change-subscription' 'category' category.pk 'subscribe' %}?next={{ request.path }}">
                {% csrf_token %}
                <input type="hidden" name="redirect_to" value="{{ request.get_full_path }}">
                <button type="submit" class="btn btn-xs btn-success">Subscribe!</button>
              </form>
            {% elif subscribed %}
              <form method="post" action="{% url 'subscription:change-subscription' 'category' category.pk 'unsubscribe' %}?next={{ request.path }}">
                {% csrf_token %}
                <input type="hidden" name="redirect_to" value="{{ request.get_full_path }}">
                <button type="submit" class="btn btn-xs btn-danger">Unsubscribe!</button>
              </form>
            {% endif %}
            <p style="margin-bottom: 0"><strong>Subscribers:</strong> {{ subscribers_count }} </p>
          </div>
        {% endif %}

        {% if perms.blog.add_post %}
            <a class="btn btn-success float-end text-white" href="{% url 'blog:create-post' %}">Create new post!</a>
        {% endif %}

        {% for post in post_list %}
          {% include 'blog/includes/posts.html' %}
        {% endfor %}
      </div>
      {% include 'blog/includes/filtering.html' %}
    </div>
  </div>
  {% include 'includes/base_pagination.html' %}
{% endblock content %}