api/urls.py
from django.urls import include, path

from api.spectacular.urls import urlpatterns as doc_urls
from users.urls import drf_urlpatterns as user_urls
from blog.urls import drf_urlpatterns as blog_urls
from rating.urls import drf_urlpatterns as rating_urls
from subscription.urls import drf_urlpatterns as subscriptions_urls

app_name = 'api'
urlpatterns = [path(r'auth/', include('djoser.urls.jwt')),]

urlpatterns += doc_urls
urlpatterns += user_urls
urlpatterns += blog_urls
urlpatterns += rating_urls
urlpatterns += subscriptions_urls

config/urls.py
from ckeditor_uploader.views import upload, browse
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import permission_required
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.generic import RedirectView
from drf_spectacular.views import SpectacularAPIView

from . import settings

admin.site.site_header = 'Blog project'
admin.site.site_title = 'Blog'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('blog/', include('blog.urls')),
    path('blog/', include('rating.urls')),
    path('blog/', include('subscription.urls')),
    path('', RedirectView.as_view(url='blog/index/')),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
]

#CKEditor
upload_view = permission_required('blog.add_post')(upload)
browse_view = never_cache(permission_required('blog.add_post')(browse))
urlpatterns += [
    path('ckeditor/upload/', upload_view, name='ckeditor_upload'),
    path('ckeditor/browse/', browse_view, name='ckeditor_browse'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')), ]

subscription/urls.py
from django.urls import path

from subscription.views import subscriptions, favorites, feed
from subscription.api.views import favorites as api_favorites
from subscription.api.views import feed as api_feed
from subscription.api.views import subscriptions as api_subs

app_name = 'subscription'

urlpatterns = [
    path('my/', feed.FeedListView.as_view(), name='my-feed'),
    path('my-subscription/', subscriptions.MySubscriptionsListView.as_view(), name='my-subscriptions'),
    path('change-subscription/<str:object_type>/<int:object_id>/<str:action>/',
         subscriptions.ChangeSubscriptionView.as_view(),
         name='change-subscription'),

    path('my-favorites/', favorites.FavoritesView.as_view(), name='my-favorites'),
    path('change-favorite/<int:post_id>/<str:action>/',
         favorites.ChangeFavoriteView.as_view(),
         name='change-favorite'),
]

drf_urlpatterns = [
    path('my_favorites/', api_favorites.MyFavoritesAPIView.as_view(), name='my-favorites'),
    path('post/<int:pk>/add-favorite/', api_favorites.AddFavoriteAPIView.as_view(), name='add-favorite'),
    path('post/<int:pk>/remove-favorite/', api_favorites.RemoveFavoriteAPIView.as_view(), name='remove-favorite'),
    path('my-feed/', api_feed.MyFeedAPIView.as_view(), name='my-feed'),
    path('my-subscriptions/users/', api_subs.MyUserSubscriptionsAPIView.as_view(), name='my-user-subscriptions'),
    path('my-subscriptions/categories/', api_subs.MyCategoriesSubscriptionsAPIView.as_view(), name='my-categories-subscriptions'),
    path('user/<int:pk>/subscribe/', api_subs.UserSubscribeAPIView.as_view(), name='user-subscribe'),
    path('user/<int:pk>/unsubscribe/', api_subs.UserUnsubscribeAPIView.as_view(), name='user-unsubscribe'),
    path('category/<int:pk>/subscribe/', api_subs.CategorySubscribeAPIView.as_view(), name='category-subscribe'),
    path('category/<int:pk>/unsubscribe/', api_subs.CategoryUnsubscribeAPIView.as_view(), name='category-unsubscribe'),
]

users/urls.py
from django.urls import path
from users.views import users
from users.api.views import users as users_api


app_name = 'users'
urlpatterns = [
    path('signup/', users.SignUpView.as_view(), name='signup'),
    path('profile/<int:pk>/', users.UserProfileView.as_view(), name='profile'),
    path('<int:pk>/edit/', users.UserProfileEditView.as_view(), name='profile-edit'),
]

drf_urlpatterns = [
    path('signup/', users_api.SignUpAPIView.as_view(), name='signup'),
    path('change-password/', users_api.ChangePasswordAPIView.as_view(), name='change-password'),
    path('me/', users_api.MeAPIView.as_view(), name='me'),
    path('me/full/', users_api.FullMeAPIView.as_view(), name='me-full'),
    path('users/<int:pk>/', users_api.UserProfileAPIView.as_view(), name='user-profile'),
    path('users/<int:pk>/full/', users_api.FullUserProfileAPIView.as_view(), name='user-profile-full'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django_resized import ResizedImageField
from phonenumber_field.modelfields import PhoneNumberField

from users.managers import CustomUserManager


class User(AbstractUser):
    email = models.EmailField(unique=True)
    phone_number = PhoneNumberField('Phone number', unique=True, blank=True, null=True)

    group_choices = (
        ('Readers', 'Readers'),
        ('Bloggers', 'Bloggers')
    )

    objects = CustomUserManager()

    @property
    def fullname(self) -> str:
        # res = f'{self.first_name}' + ' ' + f'{self.last_name}'
        # return ' '.join(res.split()) if len(res) > 1 else 'No Name'  # 1 is space symbol
        if self.first_name and self.last_name:
            return f'{self.first_name} {self.last_name}'
        elif self.first_name:
            return self.first_name
        elif self.last_name:
            return self.last_name
        else:
            return 'No Name'

    @property
    def subscribers_count(self) -> int:
        return self.subscribers.count()

    def get_absolute_url(self):
        return reverse('users:profile', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        super().save(*args, **kwargs)
        if is_new:
            Profile.objects.create(user=self)


class Profile(models.Model):
    user = models.OneToOneField('User', on_delete=models.CASCADE, primary_key=True, related_name='profile')
    telegram_id = models.CharField('Telegram', max_length=30, null=True, blank=True)
    photo = ResizedImageField(size=[300, 300],
                              upload_to='profile_photos/',
                              default='default/no-ava.png',
                              force_format='PNG')

    def __str__(self):
        return f'{self.user} (id={self.pk})'

    def get_absolute_url(self):
        return reverse('users:profile', kwargs={'pk': self.pk})

users/api/views/users.py
from django.contrib.auth import get_user_model
from django.db.models import Prefetch
from drf_spectacular.utils import extend_schema_view, extend_schema
from rest_framework import generics
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework.status import HTTP_204_NO_CONTENT

from blog.api.serializers.endpoints import comments as comments_s
from blog.api.serializers.endpoints import posts as post_s
from blog.models import Comment, Post
from users.api.serializers.endpoints import users as user_s
from users.api.serializers.nested import profile as profile_s
from users.api.services import UserProfileService

User = get_user_model()


@extend_schema_view(
    post=extend_schema(
        description="Allows a new user to create an account by providing necessary information.",
        summary='Sign up',
        tags=['Authentication & Authorization']
    ),
)
class SignUpAPIView(generics.CreateAPIView):
    permission_classes = (AllowAny,)
    queryset = User.objects.all()
    serializer_class = user_s.SignUpSerializer


@extend_schema_view(
    put=extend_schema(
        description="Allows the authenticated user to change their password by providing the `old password` and the `new password`.",
        summary='Change password',
        tags=['Authentication & Authorization']
    ),
)
class ChangePasswordAPIView(generics.GenericAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = user_s.ChangePasswordSerializer

    def put(self, request, *args, **kwargs):
        user = request.user
        serializer = user_s.ChangePasswordSerializer(instance=user, data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(status=HTTP_204_NO_CONTENT)


@extend_schema_view(
    get=extend_schema(
        description="Retrieves the profile of the currently authenticated user, including basic information.",
        summary='View my profile (brief)',
        tags=['User profile']
    ),
    patch=extend_schema(
        description="Updates specific fields of the authenticated user's profile.",
        summary='Edit my profile',
        tags=['User profile']
    ),
    put=extend_schema(
        description="Replaces the entire profile information of the authenticated user with the new provided values.",
        summary='Replace my profile',
        tags=['User profile']
    ),
)
class MeAPIView(generics.RetrieveUpdateAPIView):
    permission_classes = (IsAuthenticated,)
    queryset = User.objects.all()
    serializer_class = user_s.MeSerializer

    def get_queryset(self):
        return User.objects.select_related(
            'author',
            'profile',
        ).prefetch_related(
            'subscribers',
        )

    def get_object(self):
        return self.get_queryset().get(pk=self.request.user.pk)


@extend_schema_view(
    get=extend_schema(
        description="Retrieves the complete profile of the authenticated user, including posts, comments, and their rating.",
        summary='View my full profile (with posts and comments)',
        tags=['User profile']
    ),
)
class FullMeAPIView(generics.RetrieveAPIView):
    permission_classes = (IsAuthenticated,)
    queryset = User.objects.all()
    serializer_class = user_s.FullMeSerializer

    def get_queryset(self):
        comments_prefetch = Prefetch('comments', Comment.objects.get_comments())
        posts_prefetch = Post.objects.get_posts_prefetch(request_user=self.request.user)

        return User.objects.select_related(
            'author',
            'profile',
        ).prefetch_related(
            'subscribers',
            comments_prefetch,
            posts_prefetch
        )

    def get_object(self):
        self.object = self.get_queryset().get(pk=self.request.user.pk)

        UserProfileService.enrich_object(
            obj=self.object,
            post_serializer=profile_s.MyPostsListSerializer,
            comment_serializer=profile_s.MyCommentsListSerializer,
            request=self.request,
        )

        return self.object

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context.update({
            'posts': self.object.paginated_posts,
            'comments': self.object.paginated_comments
        })
        return context


@extend_schema_view(
    get=extend_schema(
        description="Retrieves a brief profile of a user by their `ID`, excluding detailed information like posts, comments, and rating.",
        summary='View user profile by ID (brief)',
        tags=['User profile']
    ),
)
class UserProfileAPIView(generics.RetrieveAPIView):
    queryset = User.objects
    serializer_class = user_s.UserProfileSerializer

    def get_queryset(self):
        return User.objects.select_related(
            'author',
            'profile',
        )

    def get_object(self):
        self.object = super().get_object()

        if self.request.user:
            UserProfileService.add_subscription_info(self.object, self.request.user)

        return self.object


@extend_schema_view(
    get=extend_schema(
        description="Retrieves a detailed profile of a user by their `ID`, including their posts and comments.",
        summary='View user profile by ID (with their posts and comments)',
        tags=['User profile']
    ),
)
class FullUserProfileAPIView(generics.RetrieveAPIView):
    queryset = User.objects
    serializer_class = user_s.FullUserProfileSerializer

    def get_queryset(self):
        comm_prefetch_kwargs = {}
        if self.request.user.is_authenticated:
            comm_prefetch_kwargs = {'request_user': self.request.user}
        comments_prefetch = Prefetch('comments', Comment.objects.get_comments(**comm_prefetch_kwargs))

        posts_prefetch = Post.objects.get_posts_prefetch(request_user=self.request.user)

        return User.objects.select_related(
            'author',
            'profile',
        ).prefetch_related(
            comments_prefetch,
            posts_prefetch
        )

    def get_object(self):
        self.object = super().get_object()
        get_object_kwargs = {
            'obj': self.object,
            'post_serializer': post_s.PostSerializer,
            'comment_serializer': comments_s.CommentListSerializer,
            'request': self.request,
        }

        if self.request.user.is_authenticated:
            get_object_kwargs['request_user'] = self.request.user

        UserProfileService.enrich_object(**get_object_kwargs)

        return self.object

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context.update({
            'posts': self.object.paginated_posts,
            'comments': self.object.paginated_comments
        })
        return context

users/views/users.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.core.paginator import Paginator
from django.db.models import Prefetch, Sum
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView

from blog.models import Post, Comment
from users.forms import CreationForm, UserProfileForm

User = get_user_model()


class UserProfileView(DetailView):
    model = User
    context_object_name = 'profile'

    def _paginate_objects(self, objects, paginate_by, url_kwarg):
        paginator = Paginator(objects, paginate_by)
        page = self.request.GET.get(url_kwarg, 1)
        return paginator.get_page(page)

    def get_queryset(self):
        comments_prefetch = Prefetch('comments', Comment.objects.get_comments(request_user=self.request.user))
        posts_prefetch = Post.objects.get_posts_prefetch(request_user=self.request.user)

        return User.objects.select_related(
            'author',
            'profile',
        ).prefetch_related(
            comments_prefetch,
            posts_prefetch
        )

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)

        request_user = self.request.user

        comments = obj.comments.all()
        comments_rating = comments.aggregate(Sum('rating'))['rating__sum'] or 0
        try:
            # If the user is in the "Bloggers" group, they have an instance of the Author model.
            posts = obj.author.posts.all()
            posts_rating = posts.aggregate(Sum('rating'))['rating__sum'] or 0
        except ObjectDoesNotExist:
            posts = Post.objects.none()
            posts_rating = 0

        self.rating = comments_rating + posts_rating

        obj.paginated_comments = self._paginate_objects(
            objects=comments,
            paginate_by=5,
            url_kwarg='comments_page'
        )
        obj.paginated_posts = self._paginate_objects(
            objects=posts,
            paginate_by=2,
            url_kwarg='posts_page'
        )

        obj.user_subscribed = obj.subscribers.filter(subscriber_id=request_user.id)

        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'posts': self.object.paginated_posts,
            'comments': self.object.paginated_comments,
            'rating': self.rating,
            'subscribed': self.object.user_subscribed,
        })

        return context


class UserProfileEditView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/user_form.html'

    def get_object(self, *args, **kwargs):
        obj = super().get_object(*args, **kwargs)
        if obj != self.request.user:
            raise PermissionDenied()
        return obj

    def get_queryset(self):
        return User.objects.select_related('profile')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request

        return kwargs


class SignUpView(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/sign_up.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('blog:index')
        return super().dispatch(request, *args, **kwargs)

users/templates/users/user_detail.html
{% extends "base.html" %}

{% block title %}
  <title>{{ object.username }}'s Profile</title>
{% endblock title %}

{% block content %}
  <div class="text-center user-profile">
    <div>
      <h1>{{ object.username }}
      </h1>
      <p><strong>Rating:</strong> {% include 'includes/rating_color.html' with rating=rating %}</p>
    </div>

    <img src="{{ object.profile.photo.url }}" alt="user profile photo" width="150" height="150" class="img-thumbnail">

    <p>{{ object.author.bio }}</p>
    <p><strong>Join date:</strong> {{ object.date_joined }}</p>
    {% with object.profile.telegram_id|cut:'@' as user_telegram %}
      {% if user_telegram != 'None' %}
        <a><strong>Telegram:</strong>
        <a href="https://t.me/{{ user_telegram }}" target="_blank"> @{{ user_telegram }}</a>
      {% endif %}
    {% endwith %}
    <p><strong>Subscribers:</strong> {{ object.subscribers_count }} </p>
    <div>
      {% if object != request.user %}
        {% if not subscribed %}
          <form method="post"
                action="{% url 'subscription:change-subscription' 'user' object.pk 'subscribe' %}?next={{ request.path }}">
            {% csrf_token %}
            <button type="submit" class="btn btn-success">Subscribe!</button>
          </form>
        {% else %}
          <form method="post"
                action="{% url 'subscription:change-subscription' 'user' object.pk 'unsubscribe' %}?next={{ request.path }}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Unsubscribe!</button>
          </form>
        {% endif %}
      {% else %}
        <a class="btn btn-warning text-white" href="{% url 'users:profile-edit' object.pk %}">Edit</a>
      {% endif %}
    </div>
  </div>

  <br>

  {# Posts and Comments #}
  <div class="container">
    <div class="row">
      <div class="col-6">
        <h2 class="text-center">Posts</h2>
        {% if posts %}
          {% for post in posts %}
            {#            {% include 'blog/includes/posts.html' %}#}
            {% include 'users/includes/user_posts_recursive.html' %}
          {% endfor %}
          {% include 'users/includes/profile_posts_pagination.html' %}
        {% else %}
          Nothing here.
        {% endif %}
      </div>
      <div class="col-6 vertical">
        <h2 class="text-center">Comments</h2>
        {% if comments %}
          {% for comment in comments %}
            {% include 'users/includes/user_comments_recursive.html' %}
          {% endfor %}
          {% include 'users/includes/profile_comments_pagination.html' %}
        {% else %}
          Nothing here
        {% endif %}
      </div>
    </div>
  </div>

{% endblock content %}

users/templates/users/user_form.html
{% extends "base.html" %}

{% block title %}
  <title>Edit my profile</title>
{% endblock title %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h2 class="mb-3">Edit Profile</h2>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}

          <!-- UserForm fields -->
          <div class="form-group mb-3">
            <label for="{{ form.user.first_name.id_for_label }}"><strong style="color:red">*</strong> First Name</label>
            <input type="text" class="form-control{% if form.user.first_name.errors %} is-invalid{% endif %}"
                   id="{{ form.user.first_name.id_for_label }}" name="{{ form.user.first_name.html_name }}"
                   placeholder="Enter first name" value="{{ form.user.first_name.value|default_if_none:'' }}">
            {% for error in form.user.first_name.errors %}
              <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
          </div>

          <div class="form-group mb-3">
            <label for="{{ form.user.last_name.id_for_label }}"><strong style="color:red">*</strong> Last Name</label>
            <input type="text" class="form-control{% if form.user.last_name.errors %} is-invalid{% endif %}"
                   id="{{ form.user.last_name.id_for_label }}" name="{{ form.user.last_name.html_name }}"
                   placeholder="Enter last name" value="{{ form.user.last_name.value|default_if_none:'' }}">
            {% for error in form.user.last_name.errors %}
              <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
          </div>

          <div class="form-group mb-3">
            <label for="{{ form.user.email.id_for_label }}"><strong style="color:red">*</strong> Email</label>
            <input type="email" class="form-control{% if form.user.email.errors %} is-invalid{% endif %}"
                   id="{{ form.user.email.id_for_label }}" name="{{ form.user.email.html_name }}"
                   placeholder="Enter email" value="{{ form.user.email.value|default_if_none:'' }}">
            {% for error in form.user.email.errors %}
              <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
          </div>

          <div class="form-group mb-3">
            <label for="{{ form.user.phone_number.id_for_label }}">Phone Number</label>
            <input type="text" class="form-control{% if form.user.phone_number.errors %} is-invalid{% endif %}"
                   id="{{ form.user.phone_number.id_for_label }}" name="{{ form.user.phone_number.html_name }}"
                   placeholder="Enter phone number" value="{{ form.user.phone_number.value|default_if_none:'' }}">
            {% for error in form.user.phone_number.errors %}
              <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
          </div>

          <!-- ProfileForm fields -->
          <div class="form-group mb-3">
            <label for="{{ form.profile.telegram_id.id_for_label }}">Telegram</label>
            <input type="text" class="form-control{% if form.profile.telegram_id.errors %} is-invalid{% endif %}"
                   id="{{ form.profile.telegram_id.id_for_label }}" name="{{ form.profile.telegram_id.html_name }}"
                   placeholder="Enter your Telegram username" value="{{  form.telegram_id.value|default_if_none:'' }}">
            {% for error in form.profile.telegram_id.errors %}
              <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
          </div>

          <div class="form-group mb-3">
            <label for="{{ form.profile.photo.id_for_label }}">Photo</label>
            <input type="file" class="form-control{% if form.profile.photo.errors %} is-invalid{% endif %}"
                   id="{{ form.profile.photo.id_for_label }}" name="{{ form.profile.photo.html_name }}">
            {% for error in form.profile.photo.errors %}
              <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
          </div>

          <button name="save_user" type="submit" class="btn btn-primary mb-2">Submit</button>
        </form>
      </div>
    </div>
  </div>


{% endblock content %}